name: CI - Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  android_tests_versions_7_to_10:
    strategy:
      matrix:
        android-version:
          - { api: 24, name: "7.0", pixel: "xl" }
          - { api: 26, name: "8.0", pixel: "2" }
          - { api: 28, name: "9", pixel: "3a" }
          - { api: 29, name: "10", pixel: "4a" }
    uses: ./.github/workflows/android-multi-version-test.yml
    with:
      android_version: ${{ matrix.android-version.name }}
      api_level: ${{ matrix.android-version.api }}
      pixel: ${{ matrix.android-version.pixel }}
      system_image: "system-images;android-${{ matrix.android-version.api }};google_apis;x86_64"
      runner_type: macos-13
      architecture: x86_64
      java_version: 17
      gradle_version: 8.13
      timezone: America/Sao_Paulo
      language: en_US.UTF-8
      locale: en_US.UTF-8
      max_parallel: 2
      timeout-minutes: 60
      commit_hash: ""
      emulator_count: 3

  android_tests_11_to_15:
    strategy:
      matrix:
        android-version:
          - { api: 30, name: "11", pixel: "5" }
          - { api: 31, name: "12", pixel: "6a" }
          - { api: 33, name: "13", pixel: "7a" }
          - { api: 34, name: "14", pixel: "8a" }
          - { api: 35, name: "15", pixel: "8a" }
    uses: ./.github/workflows/android-multi-version-test.yml
    with:
      android_version: ${{ matrix.android-version.name }}
      api_level: ${{ matrix.android-version.api }}
      pixel: ${{ matrix.android-version.pixel }}
      system_image: "system-images;android-${{ matrix.android-version.api }};google_apis;x86_64"
      runner_type: macos-13
      architecture: x86_64
      java_version: 17
      gradle_version: 8.13
      timezone: America/Sao_Paulo
      language: en_US.UTF-8
      locale: en_US.UTF-8
      max_parallel: 2
      timeout-minutes: 60
      commit_hash: ""
      emulator_count: 3